syntax error

diff --git a/autocommit b/autocommit
--- a/autocommit
+++ b/autocommit
@@ -6,7 +6,7 @@ if [ $# -ne 1 ]; then
     exit 1
 fi
 FILE=$1
-cd $FILE || { echo "cannot cd to "$FILE""; exit 1 }
+cd $FILE || { echo "cannot cd to "$FILE""; exit 1; }
 git add --all
 git commit -a -m "autocommitted"
 echo "autocommit done."
