see forest for trees

diff --git a/forester b/forester
--- a/forester
+++ b/forester
@@ -9,22 +9,38 @@ DAYS=${1:-"3"}
 BRANCH_PREFIX=${2:-"feature"}
 OUTFILE=${3:-"/tmp/forester.txt"}
 
-# print statusline at the top
-#echo -n "Forester: See the forest for the trees\n"  "$OUTFILE"
+echo "see forest for trees"
+# fail if outside a git repository
+git branch || { echo "you must be in a repository" ; exit 1 ;}
 
 ARGS="$(git branch | cut -c'3-' | grep "^$BRANCH_PREFIX" | xargs)"
 
+if [ ${#ARGS} == 0 ]; then
+{ echo "No branches matching $BRANCH_PREFIX" ; exit 1 ;}
+fi
+
 printline()
 {
-    ARG=$1
-    echo "$ARG" >> $OUTFILE
-    git log --stat --pretty=oneline --since=${DAYS}days $ARG
+    echo
+    printhrule $i
+    echo $i
+    printhrule $i
+    echo
+    git log --stat --pretty=oneline --since=${DAYS}days $1
 }
 
+printhrule()
+{
+    for j in `seq 1 ${#1}`
+    do
+        echo -n =
+    done
+    # adds a libe break
+    echo 
+}
 
 for i in ${ARGS[@]}
 do
-    printline $i >> $OUTFILE
-    echo ============================================= >> $OUTFILE
+    printline $i >> $OUTFILE    
 done
 
